### ISSUE TITLE
KeyError: 'auto-fight'

### ISSUE THREAD

**Issue by mason1002** [zjnGitHub/AutoStarRail#32]
开启线程池
线程池开启完毕
Traceback (most recent call last):
  File "D:\Code\pythonProject\AutoStarRail\main.py", line 40, in <module>
    window = MainWindow()
  File "D:\Code\pythonProject\AutoStarRail\gui\main_window.py", line 57, in __init__
    self.__init_widget()
  File "D:\Code\pythonProject\AutoStarRail\gui\main_window.py", line 74, in __init_widget
    self.navigationBar = ScriptNavigationBar(self)  # 主界面导航栏 (main window navigation bar)
  File "D:\Code\pythonProject\AutoStarRail\widgets\navigation_bar.py", line 48, in __init__
    self.__init_widget()
  File "D:\Code\pythonProject\AutoStarRail\widgets\navigation_bar.py", line 56, in __init_widget
    self.settingInterface = SettingWidget(self)  # 设置
  File "D:\Code\pythonProject\AutoStarRail\widgets\widget\setting_widget.py", line 26, in __init__
    self.__load_config()
  File "D:\Code\pythonProject\AutoStarRail\widgets\widget\setting_widget.py", line 74, in __load_config
    if json_['auto-fight']:
KeyError: 'auto-fight'

**Comment by mason1002** [comment]
![image](https://github.com/zjnGitHub/AutoStarRail/assets/5639702/3a705e1f-7061-45bd-b886-16b56dafef6b)

**Comment by icecubees** [comment]
我也遇到了这个问题😥，请问解决了吗

**Comment by icecubees** [comment]
已经解决，把setting_widget.py  74行的"auto-fight"改为"auto_fight"即可

**Comment by zjnGitHub** [comment]
已修复
